apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-game
  namespace: argocd
  labels:
    team: kbucci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL:        https://github.com/dennismuturi8/quiz-game.git
    targetRevision: main
    path:           k8s
  destination:
    server:    https://kubernetes.default.svc
    namespace: quiz-game
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration:    5s
        factor:      2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind:  Deployment
      jsonPointers:
        - /spec/replicas
