apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: quiz-game
  labels:
    app: game-service
    app.kubernetes.io/part-of: quiz-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: game-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "3001"
        prometheus.io/path:   "/health"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: game-service
          image: dennismuturi8/game-service:image_tag   # updated by CI
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "production"
          resources:
            requests: { memory: "64Mi", cpu: "50m" }
            limits:   { memory: "128Mi", cpu: "300m" }
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
