apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  namespace: quiz-game
  labels:
    app: leaderboard-service
spec:
  selector:
    app: leaderboard-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP
